### ISSUE TITLE
Crash in reachDatabase.py if reach_db if None

### ISSUE THREAD

**Issue by DamienDesroches** [SWOTAlgorithms/RiverObs#25]
In reachDatabase.py, when there is no db tile in the bounding box, it crashes :

2019-04-08 09:06:32,632 - SWOTRiver.SWOTL2 - INFO - Dataset opened
2019-04-08 09:06:32,669 - RiverObs.ReachDatabase - INFO - Extracting reaches
Traceback (most recent call last):
  File "/work/ALT/swot/swotdev/desrochesd/RiverObs/src/bin/swot_pixc2rivertile.py", line 133, in <module>
False
None (45.10738398840094, -45.107991500565809, 45.139096171236538, -45.078363810491851)
    main()
  File "/work/ALT/swot/swotdev/desrochesd/RiverObs/src/bin/swot_pixc2rivertile.py", line 110, in main
    l2pixc_to_rivertile.do_river_processing()
  File "/work/ALT/swot/swotdev/desrochesd/RiverObs/src/SWOTRiver/Estimate.py", line 123, in do_river_processing
    clip_buffer=self.config['clip_buffer'])
  File "/work/ALT/swot/swotdev/desrochesd/RiverObs/src/SWOTRiver/SWOTRiverEstimator.py", line 429, in get_reaches
    reach_db_path, self, clip=clip, clip_buffer=clip_buffer)
  File "/work/ALT/swot/swotdev/desrochesd/RiverObs/src/RiverObs/ReachDatabase.py", line 164, in __init__
    try_reach_idx = reach_db.reaches.extract(lat_lon_region.bounding_box)
AttributeError: 'NoneType' object has no attribute 'reaches'

**Comment by alexfore** [comment]
When a fatal error happens, I am supposed to have an exception.  I can make it more informative, however, this is what should happen.

**Comment by DamienDesroches** [comment]
That means we can't have a simulation on an area which doesn't interesect the River Database ?
On my version, i have replaced : 
 try_reach_idx = reach_db.reaches.extract(lat_lon_region.bounding_box)

by:
 try_reach_idx = []
 if reach_db != None:
      try_reach_idx = reach_db.reaches.extract(lat_lon_region.bounding_box)

**Comment by alexfore** [comment]
See this commit 7cac96fe2b7d841b6a84b4cadc9087178f821ffb, it will make empty output files if an Exception is raised

**Comment by DamienDesroches** [comment]
Always an error (and no output file) : 

2019-04-09 09:05:21,994 - swot_pixc2rivertile - ERROR - Unable to continue river processing: number of good points: 0 smaller than required: 100
2019-04-09 09:05:21,994 - SWOTRiver.Estimate - INFO - build_products
2019-04-09 09:05:21,994 - SWOTRiver.Estimate - WARNING - Output products are empty
Traceback (most recent call last):
  File "/work/ALT/swot/swotdev/desrochesd/swot-sds/RiverObs/src/bin/swot_pixc2rivertile.py", line 143, in <module>
    main()
  File "/work/ALT/swot/swotdev/desrochesd/swot-sds/RiverObs/src/bin/swot_pixc2rivertile.py", line 124, in main
    l2pixc_to_rivertile.build_products()
  File "/work/ALT/swot/swotdev/desrochesd/swot-sds/RiverObs/src/SWOTRiver/Estimate.py", line 269, in build_products
    self.pixc_file, self.index_file)
  File "/work/ALT/swot/swotdev/desrochesd/swot-sds/RiverObs/src/SWOTRiver/products/rivertile.py", line 50, in update_from_pixc
    self.nodes.update_from_pixc(pixc_file, index_file)
  File "/work/ALT/swot/swotdev/desrochesd/swot-sds/RiverObs/src/SWOTRiver/products/rivertile.py", line 978, in update_from_pixc
    pixc_vec = L2PIXCVector.from_ncfile(index_file)
  File "/work/ALT/swot/swotdev/desrochesd/swot-sds/RiverObs/src/SWOTRiver/products/product.py", line 380, in from_ncfile
    dataset = nc.Dataset(filename, 'r')
  File "netCDF4/_netCDF4.pyx", line 2015, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1636, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/work/ALT/swot/swotdev/desrochesd/swot-sds/run/synthetic_case/river/synthetic_40x30km_10m_res/cycle_0001_pass_0069_075R_nlcd50_darkWater_25m_CBE/pixc/pixcvec.nc'

**Comment by alexfore** [comment]
That is a different exception for a different reason.  Nevertheless it was an oversight.  It should be addressed now. I would appreciate if in the future you give more information on what problem you are trying to solve instead of just giving the traceback.

In both of these cases, the exception is not the issue, the issue was that you want it to always create an output product if the inputs are valid.  If there is some major problem with the inputs it still will not produce an output file.
